### ISSUE TITLE
kernel optimization - ec2 Instance fails Instance Status Checks after reboot

### ISSUE THREAD

**Issue by adrian7** [skx/tweaked.io#19]
I have followed the kernel (http://tweaked.io/guide/kernel/) optimization guide for an m3.medium instance, but after rebooting the instance it fails instance status checks and can't connect to it over ssh.

**Comment by skx** [comment]
I think that the [considerations page](https://tweaked.io/benchmarking/considerations/) could perhaps be more explicit about testing, and locally deciding your limits.  But regardless we're not AWS support, and this issue doesn't belong here.
